backend:
  name: github
  repo: billys-animals/sumaho.tk
  branch: master

# publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "img"

collections:
 - name: "post"
   label: "Post"
   author : "スフィア"
   folder: "content/post"
   create: true
   slug: "{{slug}}"
   fields:
   - {label: "Title", name: "title", widget: "string"}
   - {label: "Author", name: "author", widget: "string"}
   - {label: "Type", name: "type", widget: "string"} 
   - {label: "Publish Date", name: "date", widget: "datetime"}
   - {label: "Category", name: "categories", widget: "list", required: false}
   - {label: "Tag", name: "tags", widget: "list", required: false}
   - {label: "Keywords", name: "keywords", widget: "list", required: false}
   - {label: "Thumbnail Image Position", name: "thumbnailImagePosition" , widget: "select" , options: ["left", "top", "right"], required: false}
   - {label: "Thumbnail Image", name: "thumbnailImage", required: false, widget: "image"}
   - {label: "Draft" , name: "draft", required: false , widget: "boolean" , default: true}
   - {label: "Body", name: "body", widget: "markdown"}
